# Generated by Django 6.0.6 on 2026-08-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invite_reusable_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
