# Generated by Django 6.0.6 on 2026-06-07 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=100, help_text='Cost in Bot Bucks')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('accent_color', models.CharField(blank=True, default='#3DDC5F', help_text='Hex color used to theme this character card', max_length=9)),
                ('model_file', models.FileField(help_text='.glb 3D model file', upload_to='characters/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='character_previews/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='moneyverse.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_at'],
                'unique_together': {('user', 'character')},
            },
        ),
    ]
