# Generated by Django 6.0.6 on 2026-08-20 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyverse', '0002_character_is_starter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=50, help_text='Cost in Bot Bucks')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='hats/')),
                ('accent_color', models.CharField(blank=True, default='#3DDC5F', max_length=9)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Requires UserStats.is_premium to purchase (DEV-576).'),
        ),
        migrations.CreateModel(
            name='UserHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='moneyverse.hat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_at'],
                'unique_together': {('user', 'hat')},
            },
        ),
    ]
