# Generated by Django 6.0.6 on 2026-06-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('moneyverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='bot_bucks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='equipped_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moneyverse.character'),
        ),
    ]
