# Generated by Django 6.0.6 on 2026-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userstats_bot_bucks_userstats_equipped_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='money_chat_criteria',
            field=models.TextField(blank=True, help_text='Optional custom Money Chat checkpoints for this module. If set, these are merged with the AI-generated benchmarks. One criterion per line.'),
        ),
    ]
