# Generated by Django 6.0.6 on 2026-06-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_money_chat_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='onboarding_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Raw {question_id: option_id} answers.'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstats',
            name='onboarding_score',
            field=models.PositiveIntegerField(default=0, help_text='Number of onboarding questions answered correctly.'),
        ),
    ]
