# Generated by Django 6.0.6 on 2026-06-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userstats_onboarding_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier sent to/from clients (e.g. "interest").', unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('vibe', models.CharField(blank=True, help_text='Short friendly framing line.', max_length=255)),
                ('prompt', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Option id sent to clients (e.g. "a").', max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.onboardingquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
