# Generated by Django 6.0.6 on 2026-06-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_seed_onboarding_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('true_false', 'True / False'), ('mcq', 'Multiple Choice'), ('select_all', 'Select All That Apply'), ('match', 'Match the Following'), ('fill_blank', 'Fill in the Blanks')], max_length=20),
        ),
    ]
