# Generated by Django 6.0.6 on 2026-07-04 15:31

from django.db import migrations, models


# Assign an interactive input medium to each already-seeded onboarding question.
INPUT_TYPE_BY_SLUG = {
    'interest': 'scale',
    'inflation': 'scale',
    'diversification': 'truefalse',
    'bonds': 'choice',
    'mortgage': 'truefalse',
}


def set_input_types(apps, schema_editor):
    OnboardingQuestion = apps.get_model('courses', 'OnboardingQuestion')
    for slug, input_type in INPUT_TYPE_BY_SLUG.items():
        OnboardingQuestion.objects.filter(slug=slug).update(input_type=input_type)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_badges_daily_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestion',
            name='input_type',
            field=models.CharField(choices=[('choice', 'Multiple choice cards'), ('truefalse', 'True / False buttons'), ('scale', 'Slider scale')], default='choice', help_text='How the client renders the answer picker for this question.', max_length=20),
        ),
        migrations.AddField(
            model_name='userstats',
            name='onboarding_goals',
            field=models.JSONField(blank=True, default=list, help_text='Goal keys the user selected during onboarding.'),
        ),
        migrations.RunPython(set_input_types, noop),
    ]
