# Generated by Django 6.0.6 on 2026-08-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_userstats_streak_goal'),
        ('moneyverse', '0003_sprint_mobile_shared_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('category', models.CharField(choices=[('general', 'General'), ('budget', 'Budget'), ('investing', 'Investing'), ('credit', 'Credit'), ('saving', 'Saving'), ('stocks', 'Stocks')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='userstats',
            name='chat_personality',
            field=models.CharField(choices=[('chill', 'Chill friend'), ('coach', 'Coach'), ('funny', 'Funny'), ('teacher', 'Straight-up teacher')], default='chill', help_text='Tutor / Money Chat voice preset (DEV-656).', max_length=16),
        ),
        migrations.AddField(
            model_name='userstats',
            name='equipped_hat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moneyverse.hat'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='RevenueCat / admin-granted premium entitlement (DEV-576 / DEV-594).'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='metric',
            field=models.CharField(choices=[('lessons_completed', 'Lessons completed'), ('modules_completed', 'Modules completed (all lessons in module)'), ('module_completed', 'Specific module completed'), ('streak_days', 'Lesson activity streak (days)'), ('daily_claim_streak', 'Daily reward claim streak (days)'), ('daily_reward_day', 'Daily reward tier reached (1–7)'), ('bot_bucks', 'Bot Bucks balance'), ('xp', 'Total XP'), ('onboarding_score', 'Onboarding score'), ('characters_owned', 'Characters owned'), ('hats_owned', 'Hats owned'), ('friends_count', 'Accepted friends'), ('questions_correct', 'Questions answered correctly'), ('perfect_lessons', 'Perfect lessons (0 mistakes)')], max_length=30),
        ),
        migrations.AddField(
            model_name='userstats',
            name='last_money_tip',
            field=models.ForeignKey(blank=True, help_text='Last Home tip shown, so daily rotation does not repeat (DEV-661).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.moneytip'),
        ),
    ]
