# Generated by Django 6.0.6 on 2026-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='challengeparticipant',
            new_name='social_chal_challen_ffa5b8_idx',
            old_name='social_chal_challen_3d7a8c_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='social_frie_request_877cc3_idx',
            old_name='social_frie_request_8a1f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='social_frie_address_a01a66_idx',
            old_name='social_frie_addressee_4c8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='groupchallenge',
            new_name='social_grou_group_i_86ba4c_idx',
            old_name='social_grou_group_i_7f3e1b_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='social_grou_user_id_350dea_idx',
            old_name='social_grou_user_id_2a9c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='social_grou_group_i_327e3e_idx',
            old_name='social_grou_group_i_1b5e6f_idx',
        ),
    ]
