# Generated by Django 6.0.6 on 2026-07-15 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('friend_request', 'Friend request received'), ('friend_accepted', 'Friend request accepted'), ('friend_declined', 'Friend request declined'), ('announcement', 'Admin announcement')], max_length=32),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(max_length=280)),
                ('audience', models.CharField(choices=[('all', 'All active users'), ('selected', 'Selected users'), ('ios', 'Active users with an iOS device'), ('android', 'Active users with an Android device')], default='selected', max_length=16)),
                ('include_staff', models.BooleanField(default=False, help_text='Include staff/admin accounts in this campaign.')),
                ('send_push', models.BooleanField(default=True, help_text='Also send an OS push to registered devices. An in-app notification is always created.')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Optional routing data for the mobile app, as a JSON object.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('push_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_campaigns', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, help_text='Used only when the audience is “Selected users”.', related_name='admin_notification_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.notificationcampaign'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', False)), fields=('campaign', 'recipient'), name='unique_campaign_notification_recipient'),
        ),
    ]
