# Generated by Django 6.0.6 on 2026-07-31 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_notification_kind_notificationcampaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('friend_request', 'Friend request received'), ('friend_accepted', 'Friend request accepted'), ('friend_declined', 'Friend request declined'), ('friend_nudge', 'Friend nudge'), ('announcement', 'Admin announcement')], max_length=32),
        ),
        migrations.CreateModel(
            name='FriendNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sender', 'day'], name='social_frie_sender__b75970_idx'), models.Index(fields=['recipient', 'day'], name='social_frie_recipie_3edb6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'recipient', 'day'), name='unique_friend_nudge_per_day')],
            },
        ),
    ]
