# Generated by Django 6.0.6 on 2026-09-01 05:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_notification_automations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='notificationautomationdelivery',
            new_name='social_noti_automat_453788_idx',
            old_name='social_noti_automat_6e8f0d_idx',
        ),
        migrations.AlterField(
            model_name='notificationautomation',
            name='run_at_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='UTC time of day when this automation may run.'),
        ),
        migrations.AlterField(
            model_name='notificationautomation',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"inactive_days": 7} for inactive_users.'),
        ),
        migrations.AddField(
            model_name='feedpostupvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='social.feedpost'),
        ),
        migrations.AddField(
            model_name='feedpostupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedpostupvote',
            index=models.Index(fields=['post'], name='social_feed_post_id_1e8540_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostupvote',
            index=models.Index(fields=['user'], name='social_feed_user_id_716472_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedpostupvote',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_feed_post_upvote'),
        ),
    ]
