# Generated by Django 6.0.6 on 2026-09-06 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_feed_post_upvotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed/'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['visibility', 'status', '-created_at'], name='social_feed_visibil_7b5dd6_idx'),
        ),
        migrations.AddField(
            model_name='feedpostbookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='social.feedpost'),
        ),
        migrations.AddField(
            model_name='feedpostbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedpostbookmark',
            index=models.Index(fields=['post'], name='social_feed_post_id_d9748b_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostbookmark',
            index=models.Index(fields=['user', '-created_at'], name='social_feed_user_id_c14c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedpostbookmark',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_feed_post_bookmark'),
        ),
    ]
