# Generated by Django 6.0.6 on 2026-07-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('estimate', 'Estimate (guess a number)'), ('higher_lower', 'Higher / Lower (pick the bigger)'), ('sequence', 'Sequence (put in order)')], max_length=20)),
                ('item_id', models.SlugField(help_text='Stable unique id, e.g. "est_coffee". Reusing an id updates that item.', max_length=64, unique=True)),
                ('prompt', models.CharField(max_length=300)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Round-specific fields (value/unit/min/max, a/b/answer, items/order, fact…).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active items are eligible to appear in daily puzzles.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['round_type', 'item_id'],
                'indexes': [models.Index(fields=['round_type', 'is_active'], name='daily_daily_round_t_a22dcb_idx')],
            },
        ),
    ]
